GRANT USAGE
ON * . *
TO 'fisl2005'@'localhost'
IDENTIFIED BY 'fisl2005'
WITH MAX_QUERIES_PER_HOUR 0
     MAX_CONNECTIONS_PER_HOUR 0
     MAX_UPDATES_PER_HOUR 0 ;


GRANT ALL PRIVILEGES
ON `fisl2005` . *
TO 'fisl2005'@'localhost'
WITH GRANT OPTION ;

GRANT USAGE
ON * . *
TO 'papers'@'localhost'
IDENTIFIED BY 'papers'
WITH MAX_QUERIES_PER_HOUR 0
     MAX_CONNECTIONS_PER_HOUR 0
     MAX_UPDATES_PER_HOUR 0 ;

GRANT ALL PRIVILEGES
ON `fisl2005` . *
TO 'papers'@'localhost'
WITH GRANT OPTION ;
